### ISSUE TITLE
Unable to find active vault

### ISSUE THREAD

**Issue by pplavetzki** [nagyesta/lowkey-vault#256]
#### Describe the bug

Receiving an error from the `azclient` -> `"Unable to find active vault: https://127.0.0.1:8443"` I can see in the log of the container that it is reaching the endpoint:

```text
16:45:41.377  INFO [nio-8443-exec-4] c.g.n.l.c.common.CommonSecretController  : Received request to https://127.0.0.1:8443 create secret: sample using API version: 7.2
16:51:16.903  INFO [io-8443-exec-10] c.g.n.l.c.common.CommonSecretController  : Received request to https://127.0.0.1:8443 create secret: sample using API version: 7.2
16:58:14.649  INFO [nio-8443-exec-6] c.g.n.l.c.common.CommonSecretController  : Received request to https://127.0.0.1:8443 create secret: sample using API version: 7.2
17:31:47.418  INFO [nio-8443-exec-8] c.g.n.l.c.common.CommonSecretController  : Received request to https://127.0.0.1:8443 get secret: sample with version: -LATEST- using API version: 7.2
``` 

#### To reproduce

1. Deploy latest version of lowkey-vault into k8s
2. Try to access the endpoint (I'm using a port-forwarding approach)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-mock
  labels:
    app: kv-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-mock
  template:
    metadata:
      labels:
        app: kv-mock
    spec:
      containers:
        - name: kv-mock
          image: "nagyesta/lowkey-vault:1.8.35"
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kv-mock
  labels:
    app: kv-mock
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kv-mock
```

```kubectl port-forward service/kv-mock 8443:8443```

#### Expected behavior

Expecting to store and retrieve secrets from endpoint

#### Actual behavior

receive the above error

#### The command you used

```go
httpClient := PrepareClient()
co = &azsecrets.ClientOptions{
	azcore.ClientOptions{
		Logging:   policy.LogOptions{IncludeBody: true},
		Transport: &httpClient,
		Retry:     policy.RetryOptions{MaxRetries: 3},
		Telemetry:        policy.TelemetryOptions{},
		PerCallPolicies:  []policy.Policy{},
		PerRetryPolicies: []policy.Policy{},
	},
}
client, err := azsecrets.NewClient(vaultUrl, cred, co)
_, err = client.GetSecret(context.TODO(), "sample", nil)
```

#### A minimal project that can be used to reproduce the issue

If applicable. Please do NOT share sensitive information.

#### Environment

- OS: Docker Image deployed in Kubernetes v1.23.6
- Version: 
        golang 1.16
	github.com/Azure/azure-sdk-for-go/sdk/azcore v0.20.0
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.12.0
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.2.0
	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.2.0
	github.com/Azure/azure-storage-blob-go v0.14.0
        nagyesta/lowkey-vault:1.8.35
